# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wiki
email: andreynpetrov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is wiki based on Jekyll and GitHub Pages.
baseurl: "/wiki" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: smartbrood
github_username:  smartbrood

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-toc
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

repository: Smartbrood/wiki

github: [metadata]

# for jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

# for jekyll-toc
toc:
  min_level: 1 # default: 1
  max_level: 3 # default: 6


defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      category: "default"
      toc: true
  -
    scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
